services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    container_name: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Data Source=/data/users.db
    volumes:
      - ./data/user-service:/data
    ports:
      - "5001:80"

  product-service:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    container_name: product-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Data Source=/data/products.db
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    volumes:
      - ./data/product-service:/data
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq

  order-service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: order-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Data Source=/data/orders.db
      - Services__User=http://user-service
      - Services__Product=http://product-service
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - user-service
      - product-service
      - rabbitmq
    volumes:
      - ./data/order-service:/data
    ports:
      - "5005:80"

  eventhub-service:
    build:
      context: .
      dockerfile: EventHubService/Dockerfile
    container_name: eventhub-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMq__Host=rabbitmq
      - RabbitMq__VirtualHost=/
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
    depends_on:
      - rabbitmq
    ports:
      - "5007:80"

volumes: {}
